---
title: "Capstone"
author: "Elizabeth Cherrf, Stefan Lechmanik, Adam El-Kadi, Ryan Steffe, Mitchell Marinos, & Collin Travasos"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## load in code
# gonna have to do this for everyones file path

```{r}
#cherf - saved all files as excel
stanford_insights <- read_excel("C:/Users/localuser/OneDrive - nd.edu/Spring 2025/Sports Capstone/OUTPUT - Stanford '24 - Insights.xlsx")
head(standford_insights)
stanford_placement_insights <- read_excel("C:/Users/localuser/OneDrive - nd.edu/Spring 2025/Sports Capstone/OUTPUT - Stanford '24 Placement Insights.xlsx")
head(stanford_placement_insights)
stanford_demographics <- read_excel("C:/Users/localuser/OneDrive - nd.edu/Spring 2025/Sports Capstone/OUTPUT Stanford '24 Demographics.xlsx")
head(stanford_demographics)
#stef
stanford_insights <- read.csv("C:/Users/stefa/OneDrive/Documents/Capstone/OUTPUT - Stanford '24 - Insights.csv")
stanford_placement_insights <- read.csv("C:/Users/stefa/OneDrive/Documents/Capstone/OUTPUT - Stanford '24 Placement Insights.csv")
stanford_demographics <- read.csv("C:/Users/stefa/OneDrive/Documents/Capstone/OUTPUT Stanford '24 Demographics.csv")
#collin
stanford_insights <- read.csv("C:/users/cstra/capstone/OUTPUT - Stanford '24 - Insights.csv")
stanford_placement_insights <- read.csv("C:/users/cstra/capstone/OUTPUT - Stanford '24 Placement Insights.csv")
stanford_demographics <- read.csv("C:/users/cstra/capstone/OUTPUT Stanford '24 Demographics.csv")
#adam

#steffe

#marinos




```

```{r}
###Grouping by Age and Gender
stanford_demographics_age_gender_groups <- stanford_demographics %>% 
  group_by(Age, Gender) %>% 
  summarise(
    total_reach = sum(Reach, na.rm = TRUE),
    total_impressions = sum(Impressions, na.rm = TRUE),
    total_link_clicks = sum(LinkClicks, na.rm = TRUE)
  )

print(stanford_demographics_age_gender_groups)

```

